version: "3.7"

services:
  backend:
    build:
      target: develop-stage
    container_name: ${APP_NAME:-laravel}_backend
    volumes:
      - ./:/var/www
    ports:
      - ${DOCKER_SERVER_PORT:-8000}:8000
    depends_on:
      - db
  db:
    image: ${DB_CONNECTION:-mysql}:${DB_VERSION:-8.0.27}
    container_name: ${APP_NAME:-laravel}_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-passsword1!}
    ports:
      - ${DOCKER_DB_PORT:-3306}:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
